name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validates Podspecs
        run: pod spec lint --skip-import-validation
